Traceback (most recent call last):
  File "/gpfs/share/apps/miniconda3/gpu/4.9.2/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/gpfs/share/apps/miniconda3/gpu/4.9.2/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/gpfs/scratch/lt2504/image-eval/imagen/lib/python3.8/site-packages/pytorch_fid/__main__.py", line 3, in <module>
    pytorch_fid.fid_score.main()
  File "/gpfs/scratch/lt2504/image-eval/imagen/lib/python3.8/site-packages/pytorch_fid/fid_score.py", line 313, in main
    fid_value = calculate_fid_given_paths(args.path,
  File "/gpfs/scratch/lt2504/image-eval/imagen/lib/python3.8/site-packages/pytorch_fid/fid_score.py", line 253, in calculate_fid_given_paths
    raise RuntimeError('Invalid path: %s' % p)
RuntimeError: Invalid path: 086236371/
/cm/local/apps/slurm/var/spool/job27170350/slurm_script: line 19: unexpected EOF while looking for matching `"'
/cm/local/apps/slurm/var/spool/job27170350/slurm_script: line 20: syntax error: unexpected end of file
